name: CI/CD Pipeline with Docker

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t cardealer-app .
        docker save -o cardealer-app.tar cardealer-app

    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: cardealer-app
        path: cardealer-app.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean
        run: |
          ssh minsky@165.227.81.39 << 'EOF'
            cd ~/www/var/html/cardealer-app
            docker build -t cardealer-app .
            docker stop cardealer-app-container || true
            docker run -d --name cardealer-app-container -p 3000:3000 cardealer-app
          EOF
